#!/usr/bin/env bash
# Success-detection helpers for the prompt-a-peer *claude* tests, factored out
# of test.sh so they can be unit-tested against a recorded transcript fixture
# (see assertions.test.sh) without spending a live, paid agent run.
#
# Why not just trust the peer's final answer? The peer (a codex agent) is asked
# what model it runs as, but models frequently *misreport their own identity*
# in natural language -- in the recorded fixture the peer answers "gpt-5.6-sol"
# while actually running gpt-5.6-terra. So the host's final
# structured_output.model is NOT reliable evidence of which model ran. Two
# pieces of *intermediate* transcript evidence are reliable instead:
#
#   1. Skill discovery: on invoking the skill, the claude host receives a
#      user-role text event beginning "Base directory for this skill: <path>".
#      <path> is the on-disk location the skill loaded from; if it points inside
#      this repo checkout, the skill loaded from the repo (not a global install).
#
#   2. Model actually used: the peer is reached by shelling out to the `codex`
#      CLI, whose startup banner (captured in a tool_result) prints a
#      "model: <id>" line. The CLI prints that from its own config -- it is not
#      generated by the model -- so it is trustworthy.

# Normalize a filesystem path for cross-form comparison: lowercase, backslashes
# to forward slashes, and Windows drive (C:\) / WSL mount (/mnt/c) prefixes to a
# common /<drive>/ form. Lets a Git Bash path (/c/code/...) compare equal to the
# Windows path a claude CLI records in its transcript (C:\code\...).
normalize_path() {
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | tr '\\' '/' \
    | sed -E -e 's#^([a-z]):/#/\1/#' -e 's#^/mnt/([a-z])/#/\1/#'
}

# Emit the directory the skill loaded from, per the first
# "Base directory for this skill:" user text event in the transcript.
# Emits nothing if no such event is present.
extract_skill_base_dir() {
  local transcript="$1"
  grep -F 'Base directory for this skill:' "$transcript" \
    | jq -r '.message.content[]? | select(.type=="text") | .text' 2>/dev/null \
    | grep -F 'Base directory for this skill:' \
    | head -n 1 \
    | sed -E 's/^Base directory for this skill:[[:space:]]*//'
}

# Emit the model id from the codex CLI startup banner (the "model:" line inside
# a tool_result). Reflects the model the peer CLI actually launched. Emits
# nothing if no codex banner is present.
extract_codex_banner_model() {
  local transcript="$1"
  grep -F 'model:' "$transcript" \
    | jq -r '.message.content[]? | select(.type=="tool_result")
             | (.content | if type=="array" then .[].text else . end)' 2>/dev/null \
    | grep -E '^[[:space:]]*model:[[:space:]]' \
    | head -n 1 \
    | sed -E 's/^[[:space:]]*model:[[:space:]]*//'
}

# Verify a claude prompt-a-peer transcript shows (1) the skill loaded from this
# repo checkout and (2) the peer CLI launched the expected model. Prints a
# per-check diagnostic to stderr on failure; returns 0 only if both pass.
# Args: <transcript> <repo_root> <skill_relpath> <expected_model>
verify_claude_success() {
  local transcript="$1" repo_root="$2" skill_relpath="$3" expected_model="$4"
  local ok=0

  local base_dir expected_base
  base_dir="$(extract_skill_base_dir "$transcript")"
  expected_base="$repo_root/$skill_relpath"
  if [ -z "$base_dir" ]; then
    echo "  skill base directory: MISSING (no 'Base directory for this skill:' event)" >&2
    ok=1
  elif [ "$(normalize_path "$base_dir")" != "$(normalize_path "$expected_base")" ]; then
    echo "  skill base directory: '$base_dir' does not match repo checkout '$expected_base'" >&2
    ok=1
  fi

  local banner_model
  banner_model="$(extract_codex_banner_model "$transcript")"
  if [ -z "$banner_model" ]; then
    echo "  peer model: MISSING (no codex 'model:' banner line)" >&2
    ok=1
  elif [ "$banner_model" != "$expected_model" ]; then
    echo "  peer model: expected '$expected_model', banner shows '$banner_model'" >&2
    ok=1
  fi

  return $ok
}
